fn main() {
    tauri_plugin::Builder::new(&[
        "check_input_access",
        "request_input_access",
        "wikipedia_city_lookup",
        "get_action_router_settings",
        "set_action_router_settings",
        "get_functiongemma_status",
        "cancel_functiongemma_download",
        "list_functiongemma_models",
        "download_functiongemma_model",
        "load_functiongemma_model",
        "unload_functiongemma_model",
        "get_current_functiongemma_model",
        "get_context",
        "pin_context_mode",
        "unpin_context_mode",
    ])
    .build();
}
